# Introduction to Python and Jupyter

**Name:** ______________________________

This lab is a Python/Jupyter adaptation of the OpenIntro *Introduction to R and RStudio* lab.

## Goals

The goal of this lab is to introduce you to **Python** and **Jupyter notebooks**, which you will use throughout the course to learn statistical concepts, analyze real data, and communicate conclusions.

A Jupyter notebook is organized into **cells**. Markdown cells contain text, equations, and instructions. Code cells contain Python commands. Run the selected cell with **Shift+Enter**.

As the labs progress, you are encouraged to explore beyond exactly what the lab asks. Experimentation is one of the best ways to become fluent in programming.

## Getting started

We will use:

- **pandas** for tabular data
- **NumPy** for numerical arrays and calculations
- **Matplotlib** for plotting

Run the following cell first.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Make pandas output a little easier to read in notebooks.
pd.set_option("display.max_rows", 100)

### Local course data

All course data are loaded from the `./data/` folder. In this lab, the data are stored as
**CSV (comma-separated values)** files:

- `./data/arbuthnot.csv`
- `./data/present.csv`

A CSV file is a plain-text table. pandas can read a CSV file directly into a DataFrame
with `pd.read_csv()`.

In [3]:
from pathlib import Path
DATA_DIR = Path("./data")

## Load the Arbuthnot baptism data

The Arbuthnot data set refers to Dr. John Arbuthnot, an 18th-century physician,
writer, and mathematician. He studied the ratio of newborn boys to newborn girls
using London baptism records from 1629 to 1710.

The course data file is `./data/arbuthnot.csv`. We load it into a pandas DataFrame
named `arbuthnot` using `pd.read_csv()`.

In [4]:
arbuthnot = pd.read_csv(DATA_DIR / "arbuthnot.csv")
arbuthnot.head()

   year  boys  girls
0  1629  5218   4683
1  1630  4858   4457
2  1631  4422   4102
3  1632  4994   4590
4  1633  5158   4839

A pandas **DataFrame** is a table: each row is an observation and each column is a variable. Displaying the DataFrame name at the end of a code cell shows it in a scrollable table.

In [5]:
arbuthnot

    year  boys  girls
0   1629  5218   4683
1   1630  4858   4457
2   1631  4422   4102
3   1632  4994   4590
4   1633  5158   4839
5   1634  5035   4820
6   1635  5106   4928
7   1636  4917   4605
8   1637  4703   4457
9   1638  5359   4952
10  1639  5366   4784
11  1640  5518   5332
12  1641  5470   5200
13  1642  5460   4910
14  1643  4793   4617
15  1644  4107   3997
16  1645  4047   3919
17  1646  3768   3395
18  1647  3796   3536
19  1648  3363   3181
20  1649  3079   2746
21  1650  2890   2722
22  1651  3231   2840
23  1652  3220   2908
24  1653  3196   2959
25  1654  3441   3179
26  1655  3655   3349
27  1656  3668   3382
28  1657  3396   3289
29  1658  3157   3013
30  1659  3209   2781
31  1660  3724   3247
32  1661  4748   4107
33  1662  5216   4803
34  1663  5411   4881
35  1664  6041   5681
36  1665  5114   4858
37  1666  4678   4319
38  1667  5616   5322
39  1668  6073   5560
40  1669  6506   5829
41  1670  6278   5719
42  1671  6449   6061
43  1672  6443   6120
44  1673  6073   5822
45  1674  6113   5738
46  1675  6058   5717
47  1676  6552   5847
48  1677  6423   6203
49  1678  6568   6033
50  1679  6247   6041
51  1680  6548   6299
52  1681  6822   6533
53  1682  6909   6744
54  1683  7577   7158
55  1684  7575   7127
56  1685  7484   7246
57  1686  7575   7119
58  1687  7737   7214
59  1688  7487   7101
60  1689  7604   7167
61  1690  7909   7302
62  1691  7662   7392
63  1692  7602   7316
64  1693  7676   7483
65  1694  6985   6647
66  1695  7263   6713
67  1696  7632   7229
68  1697  8062   7767
69  1698  8426   7626
70  1699  7911   7452
71  1700  7578   7061
72  1701  8102   7514
73  1702  8031   7656
74  1703  7765   7683
75  1704  6113   5738
76  1705  8366   7779
77  1706  7952   7417
78  1707  8379   7687
79  1708  8239   7623
80  1709  7840   7380
81  1710  7640   7288

The DataFrame has 82 observations and 3 variables. In Python, use `.shape` to see the number of rows and columns, and `.columns` to see the column names.

In [6]:
arbuthnot.shape

(82, 3)

In [7]:
arbuthnot.columns

Index(['year', 'boys', 'girls'], dtype='str')

You can also inspect just the first few rows:

In [8]:
arbuthnot.head()

   year  boys  girls
0  1629  5218   4683
1  1630  4858   4457
2  1631  4422   4102
3  1632  4994   4590
4  1633  5158   4839

## Some exploratory data analysis

To select a single column, use square brackets with the column name.

In [9]:
arbuthnot["boys"]

0     5218
1     4858
2     4422
3     4994
4     5158
5     5035
6     5106
7     4917
8     4703
9     5359
10    5366
11    5518
12    5470
13    5460
14    4793
15    4107
16    4047
17    3768
18    3796
19    3363
20    3079
21    2890
22    3231
23    3220
24    3196
25    3441
26    3655
27    3668
28    3396
29    3157
30    3209
31    3724
32    4748
33    5216
34    5411
35    6041
36    5114
37    4678
38    5616
39    6073
40    6506
41    6278
42    6449
43    6443
44    6073
45    6113
46    6058
47    6552
48    6423
49    6568
50    6247
51    6548
52    6822
53    6909
54    7577
55    7575
56    7484
57    7575
58    7737
59    7487
60    7604
61    7909
62    7662
63    7602
64    7676
65    6985
66    7263
67    7632
68    8062
69    8426
70    7911
71    7578
72    8102
73    8031
74    7765
75    6113
76    8366
77    7952
78    8379
79    8239
80    7840
81    7640
Name: boys, dtype: int64

### Exercise 1

What Python command would you use to extract just the counts of girls baptized? Try it below.

In [ ]:
# Exercise 1
# Your code here:

A single DataFrame column is a pandas **Series**, which is similar to a one-dimensional vector. Python and pandas display an index along with the values; that index is not one of Arbuthnot's original variables.

### Plotting

We can create a scatterplot of the number of girls baptized per year with Matplotlib.

In [ ]:
plt.scatter(arbuthnot["year"], arbuthnot["girls"])
plt.xlabel("Year")
plt.ylabel("Girls baptized")
plt.title("Girls baptized in London")
plt.show()

To connect the observations with a line instead:

In [ ]:
plt.plot(arbuthnot["year"], arbuthnot["girls"])
plt.xlabel("Year")
plt.ylabel("Girls baptized")
plt.title("Girls baptized in London")
plt.show()

Python functions document their inputs and behavior. In Jupyter, place `?` after a function name or use `help(...)`.

In [ ]:
plt.plot?

### Exercise 2

Is there an apparent trend in the number of girls baptized over the years?

**Answer:**

## Python as a calculator

Python can evaluate ordinary mathematical expressions.

In [ ]:
5218 + 4683

pandas and NumPy also support **vectorized** calculations. Adding two Series performs the addition for every row at once.

In [ ]:
arbuthnot["boys"] + arbuthnot["girls"]

We can therefore plot total baptisms by year without writing a loop.

In [ ]:
total_births = arbuthnot["boys"] + arbuthnot["girls"]

plt.plot(arbuthnot["year"], total_births)
plt.xlabel("Year")
plt.ylabel("Total baptisms")
plt.title("Total baptisms in London")
plt.show()

The ratio of boys to girls in 1629 is:

In [ ]:
5218 / 4683

The same calculation for every year is:

In [ ]:
arbuthnot["boys"] / arbuthnot["girls"]

The **proportion** of newborns that are boys in 1629 is:

In [ ]:
5218 / (5218 + 4683)

and for every year:

In [ ]:
boy_proportion = arbuthnot["boys"] / (arbuthnot["boys"] + arbuthnot["girls"])
boy_proportion

As with a calculator, pay attention to the order of operations and use parentheses when needed.

### Exercise 3

Make a plot of the proportion of boys over time. What do you see?

In [ ]:
# Exercise 3
# Your code here:

**Answer:**

## Comparisons and Boolean data

Python comparison operators include `>`, `<`, `>=`, `<=`, `==`, and `!=`.

For example, ask whether boys outnumbered girls in each year:

In [ ]:
arbuthnot["boys"] > arbuthnot["girls"]

The result contains Boolean values: `True` or `False`. Boolean masks become especially useful later when we subset data.

## Saving your work

A notebook stores the code, Markdown, and any saved outputs in a single `.ipynb` file. Use **File → Save Notebook** (or the save shortcut in your Jupyter environment) regularly.

Unlike the original RStudio workflow, you normally do not save a hidden "workspace." Instead, the notebook itself records the analysis. When you reopen it, use **Run All** to reproduce your results from the beginning.

# On Your Own: Present-day U.S. birth records

Repeat the analysis using present-day U.S. birth records.

In [ ]:
present = pd.read_csv(DATA_DIR / "present.csv")
present.head()

Answer the following questions.

1. What years are included in this data set? What are the dimensions of the DataFrame and what are the variable names?
2. How do these counts compare with Arbuthnot's? Are they on a similar scale?
3. Does Arbuthnot's observation about boys being born in greater proportion than girls hold up in the U.S. data?
4. Make a plot that displays the boy-to-girl ratio for every year in the data set. What do you see?
5. In what year did the U.S. have the greatest total number of births?

Use the code cells below for your analysis.

In [ ]:
# Question 1

In [ ]:
# Question 2

In [ ]:
# Question 3

In [ ]:
# Question 4

In [ ]:
# Question 5

## Attribution

This lab is adapted from an OpenIntro lab released under the **Creative Commons Attribution-ShareAlike 3.0 Unported License**. The original lab was adapted for OpenIntro by Andrew Bray and Mine Çetinkaya-Rundel from a lab written by Mark Hansen of UCLA Statistics.

Python/Jupyter adaptation for course use, 2026.